### ISSUE TITLE
__init__.py

### ISSUE THREAD

**Issue by VaeBoss** [syanga/ksvd-sparse-dictionary#1]
hi,  I can't get the content from the __init__.py, please update it, thank you

**Comment by syanga** [comment]
Leaving __init__.py blank is fine, although you might want to add import statements depending on your higher level project structure, if any

**Comment by VaeBoss** [comment]
Hello, we know that the dictionary D is multiplied by the sparse coefficient X to get the original signal Data. Unfortunately, when I do not specify the initial dictionary, the dimension of the sparse coefficient is missing:
For example: the signal dimension is 64 * 8000, the dictionary dimension is: 64 * 600, but the dimension of the sparse coefficient is 600 * 7400, I don't know where the problem is, please answer, thank you

**Comment by syanga** [comment]
If your signal data has dimension 64 * 8000, your dictionary needs to have dimension 64 * m and your sparse coefficient needs dimension m * 8000, for any dimension m (or reverse the 64 and 8000, depending on what you need). This is true if your signal data is decomposed as: Data = D * X.

If you provide a more specific example of your code, I could try to help.
