### ISSUE TITLE
Dictionary and sparse coefficient initialization

### ISSUE THREAD

**Issue by VaeBoss** [syanga/ksvd-sparse-dictionary#2]
Sorry, these two codes are correct when initializing the dictionary and sparse coefficients.        

Y = Data[:,np.delete(idx_set, idxs)]         
X = np.zeros([num_atoms, Data.shape[1] - num_atoms]) 
![image](https://user-images.githubusercontent.com/43496872/57345392-4260c680-717d-11e9-9e46-4b2fa135c63b.png)

**Comment by syanga** [comment]
This looks right, in comparison to what's in the repository.
